In [63]:
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor
from sklearn.tree import  DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score,recall_score,f1_score,confusion_matrix,accuracy_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [64]:
from sklearn.datasets import make_classification
X,y=make_classification (n_samples=100,n_features=5,n_classes=2,random_state=42)

In [65]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [66]:
base_model=DecisionTreeClassifier(max_depth=1)
model=AdaBoostClassifier(estimator=base_model,n_estimators=70,random_state=42)
model.fit(Xtrain,ytrain)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=70, random_state=42)

In [67]:
ypred=model.predict(Xtest)
ypred

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1])

In [68]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("TestingEfficiency :",model.score(Xtest,ytest))

Training Efficiency : 1.0
TestingEfficiency : 0.8

In [69]:
confusion_matrix(ytest,ypred)

array([[11,  1],
       [ 5, 13]])

In [70]:
print('Precision score',precision_score(ytest,ypred))
print('Recall Score',recall_score(ytest,ypred))

Precision score 0.9285714285714286
Recall Score 0.7222222222222222

In [71]:
df=pd.read_csv(r"C:\Users\ASUS\Downloads\taxi_trip_pricing (1).csv")
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [72]:
df = df.dropna()
df=df.drop(['Weather', 'Passenger_Count', 'Traffic_Conditions','Day_of_Week'], axis=1)
df

,Trip_Distance_km,Time_of_Day,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,2.32,1.26,0.34,41.72,28.9914
...,...,...,...,...,...,...,...
990,40.17,Evening,3.81,0.66,0.42,62.66,56.6394
992,14.34,Afternoon,3.23,1.01,0.29,45.07,30.7837
994,18.69,Evening,4.90,1.79,0.17,79.41,51.8548
995,5.49,Afternoon,2.39,0.62,0.49,58.39,34.4049
998,47.56,Morning,2.67,0.82,0.17,114.94,61.2090

In [73]:
X = df.drop('Trip_Price',axis=1)
y = df['Trip_Price']

In [74]:
X=pd.get_dummies(df,dtype=int,drop_first=True)
X.head()

,Trip_Distance_km,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night
0,19.35,3.56,0.80,0.32,53.82,36.2624,0,1,0
2,36.87,2.70,1.21,0.15,37.27,52.9032,1,0,0
5,8.64,2.55,1.71,0.48,89.33,60.2028,0,0,0
12,41.79,4.60,1.77,0.11,86.95,88.1328,0,0,1
14,9.91,2.32,1.26,0.34,41.72,28.9914,1,0,0

In [75]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [76]:
base_model=DecisionTreeRegressor(max_depth=1)
model=AdaBoostRegressor(estimator=base_model,n_estimators=89,random_state=42)
model.fit(Xtrain,ytrain)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=1), n_estimators=89,
                  random_state=42)

In [77]:
ypred=model.predict(Xtest)
ypred

array([ 54.81831526,  58.90121518,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  58.90121518,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  58.90121518,
        58.90121518,  54.81831526, 275.37927118,  54.81831526,
        54.81831526,  58.90121518,  58.90121518,  58.90121518,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  58.90121518,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        58.90121518,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526, 275.37927118,  54.81831526,  58.90121518,
        58.90121518, 275.37927118,  58.90121518,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  58.90121518,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        58.90121518,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526, 275.37927118,  54.81831526,
        54.81831526,  54.81831526,  54.81831526, 275.37927118,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  58.90121518,  54.81831526,  54.81831526,
        54.81831526,  58.90121518,  54.81831526,  54.81831526,
        58.90121518,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        58.90121518,  54.81831526,  54.81831526,  54.81831526,
        54.81831526,  54.81831526,  58.90121518,  54.81831526,
        54.81831526,  54.81831526,  54.81831526,  54.81831526,
        58.90121518,  54.81831526,  54.81831526,  58.90121518,
        54.81831526])

In [78]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.6734312527168049
Training Efficiency : 0.7366354256887304

In [79]:
print("MAE :", mean_absolute_error(ytest, ypred))
print("MSE :", mean_squared_error(ytest, ypred))
print("R2 Score :", r2_score(ytest, ypred))

MAE : 19.718998920401447
MSE : 572.31008511867
R2 Score : 0.7366354256887304