In [1]:
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.datasets import load_breast_cancer

In [2]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\house_price_regression_dataset.csv")

In [3]:
#divide the data into input and output feature
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [4]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [5]:
model=GradientBoostingRegressor(n_estimators=300)
model.fit(Xtrain,ytrain)

GradientBoostingRegressor(n_estimators=300)

In [6]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.9995244930475269
Training Efficiency : 0.9967881716446899

In [7]:
ypred=model.predict(Xtest)

In [8]:
print("R2 ",r2_score(ytest,ypred))
print("MAE: ",mean_absolute_error(ytest,ypred))

R2  0.9967881716446899
MAE:  11559.649208661005

In [9]:
#classifiers
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score,recall_score,f1_score,confusion_matrix,accuracy_score

In [10]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\bankloan.csv")
df

,ID,Age,Experience,Income,ZIP.Code,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

In [11]:
df = df.drop(['ID', 'ZIP.Code'], axis=1)
df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

In [12]:

#keep personal loan as y
X=df.drop("Personal.Loan",axis=1)
y=df["Personal.Loan"]
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal.Loan, Length: 5000, dtype: int64

In [13]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [14]:
model=GradientBoostingClassifier(n_estimators=300,learning_rate=0.02)
model.fit(Xtrain,ytrain)

GradientBoostingClassifier(learning_rate=0.02, n_estimators=300)

In [15]:
ypred=model.predict(Xtest)
ypred

array([0, 1, 0, ..., 0, 0, 1], shape=(1500,))

In [16]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Testing Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.99
Testing Efficiency : 0.988

In [17]:
confusion_matrix(ytest,ypred)

array([[1340,    3],
       [  15,  142]])

In [18]:
print('Precision score',precision_score(ytest,ypred))
print('Recall Score',recall_score(ytest,ypred))
print('Accuracy Score',accuracy_score(ytest,ypred))

Precision score 0.9793103448275862
Recall Score 0.9044585987261147
Accuracy Score 0.988