In [140]:
import pandas as pd
import numpy as np#by default average set to be binary,when we have multi class data in output columns different then we use weighted
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [141]:
                #Taxi trip pricing for regression if cleaning is required then 
df=pd.read_csv(r"C:\Users\ASUS\Downloads\taxi_trip_pricing (1).csv")
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [142]:
df = df.dropna()
df=df.drop(['Weather', 'Passenger_Count', 'Traffic_Conditions','Day_of_Week'], axis=1)
df

,Trip_Distance_km,Time_of_Day,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,2.32,1.26,0.34,41.72,28.9914
...,...,...,...,...,...,...,...
990,40.17,Evening,3.81,0.66,0.42,62.66,56.6394
992,14.34,Afternoon,3.23,1.01,0.29,45.07,30.7837
994,18.69,Evening,4.90,1.79,0.17,79.41,51.8548
995,5.49,Afternoon,2.39,0.62,0.49,58.39,34.4049
998,47.56,Morning,2.67,0.82,0.17,114.94,61.2090

In [143]:
X = df.drop('Trip_Price',axis=1)
y = df['Trip_Price']

In [144]:
X=pd.get_dummies(df,dtype=int,drop_first=True)
X.head()

,Trip_Distance_km,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night
0,19.35,3.56,0.80,0.32,53.82,36.2624,0,1,0
2,36.87,2.70,1.21,0.15,37.27,52.9032,1,0,0
5,8.64,2.55,1.71,0.48,89.33,60.2028,0,0,0
12,41.79,4.60,1.77,0.11,86.95,88.1328,0,0,1
14,9.91,2.32,1.26,0.34,41.72,28.9914,1,0,0

In [145]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [146]:
Knr=KNeighborsRegressor(n_neighbors=5)
Knr.fit(Xtrain,ytrain)

KNeighborsRegressor()

In [147]:
KNeighborsRegressor()

KNeighborsRegressor()

In [148]:
ypredc=Knr.predict(Xtest)
ypredc

array([ 41.77814   ,  87.45154   ,  44.80328   ,  53.84436   ,
        44.91988   ,  23.4651    ,  69.34748   ,  36.32368   ,
        55.53612   ,  59.26026   ,  19.42384   ,  54.87896   ,
        54.84488   ,  56.6183    ,  10.6242    ,  75.03594   ,
        74.24038   ,  62.585     ,  41.38696   ,  36.77122   ,
        26.47274   ,  39.203     ,  98.23488   ,  32.59382   ,
        42.68196   ,  59.11904   ,  55.25724   ,  52.05854   ,
        15.81654   ,  66.04534   ,  33.37892   ,  38.46586   ,
        69.05882   ,  43.58426   ,  58.03492   ,  81.62664   ,
        94.08428   ,  51.43116   , 316.6550981 ,  20.4691    ,
        45.91102   ,  76.04082   ,  78.63286   ,  92.93296   ,
        33.06202   ,  74.23896   ,  39.95042   ,  50.87568   ,
        44.9643    ,  32.4672    ,  76.50134   ,  59.93686   ,
        30.33292   ,  23.25864   ,  51.82      , 103.6321    ,
        56.04288   ,  27.44718   ,  50.18012   ,  71.8034    ,
        60.61742   ,  41.02652   ,  27.34432   ,  32.34958   ,
       102.83674   ,  41.79626   ,  57.98138   ,  30.33234   ,
        28.56786   ,  28.93112   ,  28.73856   ,  37.5907    ,
        37.6161    ,  68.0519    ,  45.74864   ,  49.40034   ,
        34.98996   , 247.87574947,  57.1555    ,  97.3828    ,
        86.80458   , 306.24886362,  90.0696    ,  42.53398   ,
        40.92798   ,  23.70736   ,  72.47542   ,  47.86424   ,
        68.30566   ,  47.59812   ,  95.1207    ,  26.48836   ,
        43.2693    ,  59.87994   ,  14.77416   ,  75.07678   ,
        17.28296   ,  67.68862   ,  22.26522   ,  48.431     ,
       115.99984   ,  33.99378   ,  26.11598   ,  26.75658   ,
        63.10304   ,  46.4795    ,  56.76872   ,  36.917     ,
        36.49404   ,  58.03492   , 317.11620009,  50.87568   ,
        24.92306   ,  57.9196    ,  36.51872   , 290.25373154,
        23.57856   ,  45.56702   ,  33.19156   ,  69.34748   ,
        21.16102   ,  38.8152    ,  53.64806   ,  29.75312   ,
        65.90228   ,  86.84314   ,  25.74422   ,  24.91936   ,
        56.85388   ,  97.6973    ,  66.47218   ,  58.97072   ,
        81.53904   ,  42.29758   ,  58.1969    ,  46.67578   ,
        43.1495    ,  13.09662   ,  32.4923    ,  48.39412   ,
        32.39254   ,  67.18338   ,  34.00952   ,  33.36926   ,
        69.55818   ,  32.87598   ,  57.28966   ,  53.86402   ,
        68.30566   ,  35.76268   ,  21.67738   ,  33.30486   ,
       102.68344   ,  58.0118    ,  20.87754   ,  37.66074   ,
         8.4639    ,  37.24026   ,  76.50296   ,  45.51612   ,
        26.01832   ,  46.97662   ,  59.49356   ,  41.02652   ,
        79.22744   ,  52.1294    ,  72.11652   , 103.90996   ,
        26.54786   ])

In [149]:
print("Training Efficiency :",Knr.score(Xtrain,ytrain))
print("Training Efficiency :",Knr.score(Xtest,ytest))

Training Efficiency : 0.992741212920123
Training Efficiency : 0.9891454426669101

In [150]:
print("MAE :", mean_absolute_error(ytest, ypredc))
print("MSE :", mean_squared_error(ytest, ypredc))
print("RMSE:", np.sqrt(mean_squared_error(ytest, ypredc)))
print("R2 Score :", r2_score(ytest, ypredc))

MAE : 2.6497794522266815
MSE : 23.58773061058707
RMSE: 4.856720149502858
R2 Score : 0.9891454426669101

In [151]:
#split dataset into x and y
Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [152]:
model=SVR(kernel='linear',C=10,epsilon=0.01)

In [153]:
scaler = StandardScaler()
Xtrain = scaler.fit_transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [154]:

model.fit(Xtrain, ytrain)

SVR(C=10, epsilon=0.01, kernel='linear')

In [155]:
ypred=model.predict(Xtest)
ypred

array([ 36.10136494,  87.72538613,  43.85301832,  52.59178844,
        43.59662928,  19.36130771,  72.97521775,  36.02791949,
        51.27479634,  54.68129793,  20.00445741,  54.62125129,
        54.48994173,  58.77511836,  13.92995667,  78.19098706,
        73.37092403,  65.16165004,  41.43532986,  36.1389383 ,
        25.8095236 ,  39.23313829,  97.57744597,  31.23307049,
        43.85857552,  66.91171572,  56.7142186 ,  50.99698014,
        14.9300334 ,  68.53726172,  34.25370563,  36.50442273,
        76.42754485,  39.54453101,  58.59032004,  81.97961361,
        98.99992566,  51.0554029 , 327.19847962,  20.21022506,
        46.17161641,  78.70876668,  79.62811569, 105.14218623,
        30.40059761,  75.70937968,  40.79763019,  50.69398502,
        36.44507237,  35.00044542,  76.20725748,  60.1952354 ,
        30.77859229,  19.0990578 ,  52.63842221,  99.51468837,
        56.64604195,  28.58344299,  46.80946355,  71.63950794,
        62.05806951,  43.06825598,  26.07077752,  26.97379775,
       100.59416829,  41.29957025,  62.75264307,  29.41697409,
        28.7658281 ,  22.87430591,  25.89673731,  41.2014639 ,
        35.28105897,  66.63025109,  46.59436747,  47.99580723,
        35.35325759, 201.87852387,  58.96534906, 109.4298608 ,
        86.89608082, 296.09429292,  92.6851829 ,  44.94922885,
        38.68064471,  23.07218861,  70.84044361,  46.0219141 ,
        67.23594524,  45.92082279,  95.22946544,  26.91596635,
        40.98067336,  58.25406275,  12.99301633,  75.21890081,
        16.51521564,  68.92719414,  23.27581403,  51.61995106,
       116.41793656,  30.44807487,  19.93150943,  26.64139171,
        61.56657932,  45.02796394,  58.01681271,  39.56542109,
        35.08585871,  54.70554064, 320.96045899,  53.15777745,
        29.05941103,  61.99321723,  36.26103087, 280.89208268,
        20.27047627,  44.84455921,  33.73608544,  72.66953542,
        19.26759477,  38.25228138,  52.65021766,  32.1425297 ,
        69.471561  ,  85.45822721,  20.7833581 ,  19.8767986 ,
        57.16190744, 101.87602076,  68.44747284,  58.65201678,
        81.3983189 ,  44.62397204,  62.49283926,  49.18713717,
        42.99067516,  19.65740029,  36.53204339,  48.45233718,
        34.39541276,  61.22059129,  32.2126487 ,  32.57043077,
        71.10110244,  29.77717765,  58.08237726,  48.4565045 ,
        64.72784324,  34.95454532,  25.4780976 ,  34.34913209,
       108.97189852,  59.87451595,  20.33987186,  36.0449643 ,
         6.46091987,  30.09506078,  78.78361953,  47.6207574 ,
        22.75060093,  45.16886634,  61.88415494,  40.21675828,
        80.75431217,  54.94026141,  72.87506378, 107.70184908,
        29.97104614])

In [156]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.9999999864115592
Training Efficiency : 0.9999999867142491

In [157]:
print("mae: ",mean_absolute_error(ytest,ypred))
print("R2 Score :", r2_score(ytest, ypred))

mae:  0.00435721241349141
R2 Score : 0.9999999867142491

In [158]:
model=DecisionTreeRegressor(max_depth=5)
model.fit(Xtrain,ytrain)

DecisionTreeRegressor(max_depth=5)

In [159]:
ypred=model.predict(Xtest)
ypred

array([ 39.40675714,  88.77297619,  44.99929375,  54.30926471,
        44.99929375,  20.09249286,  71.49843667,  32.68467632,
        49.57754348,  54.30926471,  20.09249286,  54.30926471,
        54.30926471,  59.47944483,  10.77004   ,  78.62708095,
        71.49843667,  64.4476125 ,  39.40675714,  39.40675714,
        26.99618966,  39.40675714, 100.87252222,  32.68467632,
        44.99929375,  64.4476125 ,  54.30926471,  49.57754348,
        10.77004   ,  71.49843667,  32.68467632,  39.40675714,
        78.62708095,  39.40675714,  59.47944483,  78.62708095,
       100.87252222,  49.57754348, 332.04368868,  20.09249286,
        44.99929375,  78.62708095,  78.62708095, 100.87252222,
        32.68467632,  78.62708095,  39.40675714,  49.57754348,
        39.40675714,  32.68467632,  78.62708095,  59.47944483,
        32.68467632,  20.09249286,  54.30926471, 100.87252222,
        54.30926471,  26.99618966,  44.99929375,  71.49843667,
        64.4476125 ,  44.99929375,  26.99618966,  26.99618966,
       100.87252222,  39.40675714,  64.4476125 ,  26.99618966,
        26.99618966,  20.09249286,  26.99618966,  39.40675714,
        32.68467632,  64.4476125 ,  44.99929375,  49.57754348,
        32.68467632, 206.6995697 ,  59.47944483, 112.7757    ,
        88.77297619, 248.29520891,  88.77297619,  44.99929375,
        39.40675714,  20.09249286,  71.49843667,  44.99929375,
        64.4476125 ,  44.99929375, 100.87252222,  26.99618966,
        39.40675714,  59.47944483,  10.77004   ,  78.62708095,
        20.09249286,  71.49843667,  20.09249286,  49.57754348,
       112.7757    ,  32.68467632,  20.09249286,  26.99618966,
        59.47944483,  44.99929375,  59.47944483,  39.40675714,
        32.68467632,  54.30926471, 332.04368868,  54.30926471,
        26.99618966,  59.47944483,  39.40675714, 276.84059674,
        20.09249286,  44.99929375,  32.68467632,  71.49843667,
        20.09249286,  39.40675714,  54.30926471,  32.68467632,
        71.49843667,  88.77297619,  20.09249286,  20.09249286,
        59.47944483, 100.87252222,  71.49843667,  59.47944483,
        78.62708095,  44.99929375,  64.4476125 ,  49.57754348,
        44.99929375,  20.09249286,  39.40675714,  49.57754348,
        32.68467632,  59.47944483,  32.68467632,  32.68467632,
        71.49843667,  32.68467632,  59.47944483,  49.57754348,
        64.4476125 ,  32.68467632,  26.99618966,  32.68467632,
       112.7757    ,  59.47944483,  20.09249286,  32.68467632,
        10.77004   ,  32.68467632,  78.62708095,  49.57754348,
        20.09249286,  44.99929375,  59.47944483,  39.40675714,
        78.62708095,  54.30926471,  71.49843667, 112.7757    ,
        32.68467632])

In [160]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.997888841461141
Training Efficiency : 0.9914099786882663

In [161]:
print("mae: ",mean_absolute_error(ytest,ypred))
print("R2 Score :", r2_score(ytest, ypred))

mae:  2.0675515436778786
R2 Score : 0.9914099786882663

In [162]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
Xtrain=scaler.fit_transform(Xtrain)
Xtest=scaler.transform(Xtest)

In [163]:
model=RandomForestRegressor(n_estimators=200,max_depth=11)
model.fit(Xtrain,ytrain)

RandomForestRegressor(max_depth=11, n_estimators=200)

In [164]:
ypred=model.predict(Xtest)
ypred

array([ 36.30013117,  87.621458  ,  43.968042  ,  52.92133255,
        43.2331605 ,  19.86944946,  72.889457  ,  36.10433617,
        51.180558  ,  54.6302354 ,  19.95603429,  54.59234925,
        54.41358508,  58.86600712,  13.66392   ,  78.06338783,
        73.3435195 ,  65.1327965 ,  41.818019  ,  36.26962267,
        25.735062  ,  39.2274443 ,  97.44438   ,  31.233625  ,
        43.993796  ,  66.6156925 ,  56.686043  ,  50.9378835 ,
        15.1858575 ,  68.723493  ,  34.41632283,  36.6515475 ,
        76.3820975 ,  39.31380415,  58.7371987 ,  82.0098535 ,
        99.9181025 ,  50.97399   , 309.76336644,  20.14560946,
        46.319128  ,  78.7475175 ,  79.9434635 , 107.5845795 ,
        30.545138  ,  75.718187  ,  40.960521  ,  50.737737  ,
        36.271328  ,  34.7289025 ,  76.188546  ,  60.1644525 ,
        30.724156  ,  19.85276229,  52.89231255, 100.242521  ,
        56.6192045 ,  28.5964859 ,  46.43850263,  71.56352   ,
        62.0497185 ,  43.101996  ,  26.0313305 ,  27.399243  ,
       100.530826  ,  40.99692975,  62.9238855 ,  29.4340345 ,
        28.7732025 ,  23.04592417,  25.9002835 ,  41.0292815 ,
        35.10163183,  66.5626225 ,  46.43057279,  48.085518  ,
        35.30340433, 239.34016122,  58.8239385 , 110.176442  ,
        86.5259725 , 283.75952357,  93.8150825 ,  44.84000633,
        38.71318698,  23.07834433,  70.53414367,  46.0964775 ,
        67.0824415 ,  45.8438255 ,  94.995614  ,  27.4020915 ,
        40.9814775 ,  58.86410175,  12.2481765 ,  75.212855  ,
        16.748271  ,  69.1199435 ,  23.18511483,  51.6646815 ,
       119.168351  ,  30.488989  ,  20.03671629,  26.406332  ,
        61.3163595 ,  44.96480717,  57.71090875,  39.35401215,
        34.95132967,  54.65356606, 316.09283248,  53.09116583,
        29.11321383,  61.8350655 ,  36.40629267, 276.58425844,
        20.19809167,  44.71918667,  33.55588367,  72.62984317,
        19.86652313,  38.43574783,  52.9185763 ,  32.2203485 ,
        69.6413975 ,  85.481205  ,  20.7472325 ,  20.04520367,
        57.1850675 , 102.097265  ,  68.6329595 ,  58.81661875,
        81.525168  ,  44.74949475,  62.488245  ,  49.374113  ,
        43.014099  ,  19.83924033,  36.75677642,  48.4001285 ,
        34.46532467,  61.1769275 ,  32.0880577 ,  32.606529  ,
        71.380522  ,  29.9202365 ,  58.51226225,  48.3814755 ,
        65.1387115 ,  34.618115  ,  25.4492415 ,  34.4425865 ,
       108.7580705 ,  59.86800753,  20.22316117,  35.95137   ,
         8.0642865 ,  30.1408855 ,  78.843811  ,  47.984709  ,
        22.41417583,  45.25293667,  61.818332  ,  40.24218758,
        80.465696  ,  54.82597329,  72.93962267, 107.357486  ,
        29.972722  ])

In [165]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.9982312490945922
Training Efficiency : 0.9947481768428895

In [166]:
print("MAE",mean_absolute_error(ytest,ypred))

MAE 0.6521072912100362

In [167]:
#split into training and testing data
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=3,random_state=42)