In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer,fetch_california_housing
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [3]:
lbc=load_breast_cancer()
df=pd.DataFrame(lbc.data,columns=lbc.feature_names)
df
df["cancer"]=lbc.target
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,cancer
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [4]:
X=df.drop("cancer",axis=1)
y=df.cancer

In [5]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
model=RandomForestClassifier(n_estimators=150,max_depth=5)
model.fit(Xtrain,ytrain)

RandomForestClassifier(max_depth=5, n_estimators=150)

In [10]:
ypred=model.predict(Xtest)
ypred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [11]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.992462311557789
Training Efficiency : 0.9707602339181286

In [12]:
print('Accuracy score :',accuracy_score(ytest,ypred))
print('Precision score',precision_score(ytest,ypred,average="weighted"))
print('Recall Score',recall_score(ytest,ypred,average="weighted"))

Accuracy score : 0.9707602339181286
Precision score 0.9711000474158369
Recall Score 0.9707602339181286

In [ ]:
                                                  #RandomForestRegressor

In [13]:
data=fetch_california_housing()
df=pd.DataFrame(lbc.data,columns=lbc.feature_names)
df
df["target"]=lbc.target
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [14]:
X=df.drop("target",axis=1)
y=df.target

In [15]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
Xtrain=scaler.fit_transform(Xtrain)
Xtest=scaler.transform(Xtest)

In [22]:
model=RandomForestRegressor(n_estimators=200,max_depth=11)
model.fit(Xtrain,ytrain)

RandomForestRegressor(max_depth=11, n_estimators=200)

In [23]:
ypred=model.predict(Xtest)
ypred

array([1.   , 0.   , 0.   , 1.   , 1.   , 0.   , 0.   , 0.165, 0.22 ,
       0.78 , 0.715, 0.   , 0.975, 0.15 , 0.995, 0.005, 0.975, 1.   ,
       1.   , 0.   , 0.82 , 1.   , 0.   , 1.   , 1.   , 0.95 , 1.   ,
       0.8  , 1.   , 0.   , 1.   , 1.   , 0.72 , 0.985, 1.   , 1.   ,
       0.295, 0.975, 0.   , 0.94 , 1.   , 0.   , 1.   , 1.   , 0.715,
       0.995, 0.84 , 0.765, 1.   , 0.995, 0.005, 0.   , 0.78 , 0.96 ,
       1.   , 0.995, 1.   , 0.   , 0.09 , 1.   , 1.   , 0.   , 0.   ,
       0.945, 1.   , 0.965, 0.   , 0.005, 1.   , 0.99 , 0.025, 0.   ,
       0.995, 0.   , 0.995, 0.965, 0.975, 0.595, 1.   , 0.845, 0.01 ,
       1.   , 0.87 , 0.   , 0.17 , 0.005, 0.03 , 0.01 , 0.995, 1.   ,
       1.   , 0.78 , 0.685, 0.94 , 1.   , 1.   , 0.   , 0.   , 1.   ,
       0.015, 0.075, 1.   , 0.015, 0.   , 1.   , 0.995, 1.   , 0.   ,
       0.275, 0.925, 0.   , 1.   , 0.775, 0.   , 0.72 , 0.   , 1.   ,
       0.85 , 0.975, 0.   , 0.575, 1.   , 1.   , 0.   , 0.975, 0.   ,
       0.   , 1.   , 1.   , 0.   , 0.16 , 0.   , 0.845, 0.985, 0.74 ,
       0.12 , 0.35 , 1.   , 0.645, 0.035, 1.   , 0.   , 1.   , 1.   ,
       0.005, 1.   , 0.   , 0.005, 0.27 , 0.995, 0.19 , 1.   , 1.   ,
       1.   , 0.765, 0.   , 0.   , 0.985, 0.99 , 1.   , 0.89 , 0.995,
       1.   , 0.995, 0.52 , 1.   , 1.   , 0.875, 0.99 , 0.065, 0.655])

In [24]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.9774090132341446
Training Efficiency : 0.865399074074074

In [25]:
print("MAE",mean_absolute_error(ytest,ypred))

MAE 0.07491228070175437