In [145]:
import pandas as pd
from sklearn.svm import SVC,SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,mean_absolute_error, mean_squared_error, r2_score

In [146]:
import pandas as pd

df = pd.read_excel(r"C:\Users\ASUS\Downloads\bankloan.csv")
df.head()

,ID,Age,Experience,Income,ZIP.Code,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [147]:
df = df.drop(['ID', 'ZIP.Code'], axis=1)
df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

In [148]:

#keep personal loan as y
X=df.drop("Personal.Loan",axis=1)
y=df["Personal.Loan"]
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal.Loan, Length: 5000, dtype: int64

In [149]:
#split dataset into x and y
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [150]:
model=SVC(kernel='linear')

In [151]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(Xtrain, ytrain)

SVC()

In [152]:
ypredc=svc.predict(Xtest)
ypredc

array([0, 0, 0, ..., 0, 0, 0], shape=(1500,))

In [153]:
con_matrix=confusion_matrix(ytest,ypredc)
con_matrix

array([[1336,    7],
       [ 144,   13]])

In [154]:
print("Training Efficiency :",svc.score(Xtrain,ytrain))
print("Training Efficiency :",svc.score(Xtest,ytest))

Training Efficiency : 0.914
Training Efficiency : 0.8993333333333333

In [155]:
print("Accuracy: ",accuracy_score(ytest,ypredc))
print("Precision",precision_score(ytest,ypredc))
print("Recall",recall_score(ytest,ypredc))
print("F1",f1_score(ytest,ypredc))

Accuracy:  0.8993333333333333
Precision 0.65
Recall 0.08280254777070063
F1 0.14689265536723164

In [156]:
# print("MAE :", mean_absolute_error(ytest, ypredc))
# print("R2 Score :", r2_score(ytest, ypredc))

In [ ]:
                #Taxi trip pricing for regression if cleaning is required then 
df=pd.read_csv(r"C:\Users\ASUS\Downloads\taxi_trip_pricing (1).csv")
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [158]:
df = df.dropna()
df=df.drop(['Weather', 'Passenger_Count', 'Traffic_Conditions','Day_of_Week'], axis=1)
df

,Trip_Distance_km,Time_of_Day,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,2.32,1.26,0.34,41.72,28.9914
...,...,...,...,...,...,...,...
990,40.17,Evening,3.81,0.66,0.42,62.66,56.6394
992,14.34,Afternoon,3.23,1.01,0.29,45.07,30.7837
994,18.69,Evening,4.90,1.79,0.17,79.41,51.8548
995,5.49,Afternoon,2.39,0.62,0.49,58.39,34.4049
998,47.56,Morning,2.67,0.82,0.17,114.94,61.2090

In [159]:
X = df.drop('Trip_Price',axis=1)
y = df['Trip_Price']

In [ ]:
X=pd.get_dummies(df,dtype=int,drop_first=True)
X.head()

<bound method NDFrame.head of      Trip_Distance_km  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0               19.35       3.56         0.80             0.32
2               36.87       2.70         1.21             0.15
5                8.64       2.55         1.71             0.48
12              41.79       4.60         1.77             0.11
14               9.91       2.32         1.26             0.34
..                ...        ...          ...              ...
990             40.17       3.81         0.66             0.42
992             14.34       3.23         1.01             0.29
994             18.69       4.90         1.79             0.17
995              5.49       2.39         0.62             0.49
998             47.56       2.67         0.82             0.17

     Trip_Duration_Minutes  Trip_Price  Time_of_Day_Evening  \
0                    53.82     36.2624                    0
2                    37.27     52.9032                    1
5                    89.33     60.2028                    0
12                   86.95     88.1328                    0
14                   41.72     28.9914                    1
..                     ...         ...                  ...
990                  62.66     56.6394                    1
992                  45.07     30.7837                    0
994                  79.41     51.8548                    1
995                  58.39     34.4049                    0
998                 114.94     61.2090                    0

     Time_of_Day_Morning  Time_of_Day_Night
0                      1                  0
2                      0                  0
5                      0                  0
12                     0                  1
14                     0                  0
..                   ...                ...
990                    0                  0
992                    0                  0
994                    0                  0
995                    0                  0
998                    1                  0

[562 rows x 9 columns]>

In [161]:
#split dataset into x and y
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [162]:
model=SVR(kernel='linear',C=10,epsilon=0.01)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

Xtrain = scaler.fit_transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [ ]:
from sklearn.svm import SVR
model.fit(Xtrain, ytrain)

SVR()

In [ ]:
ypred=model.predict(Xtest)
ypred

array([38.19071398, 72.60417769, 46.77062761, 52.03478694, 49.2847656 ,
       22.22328497, 64.22881378, 34.3557126 , 54.49572927, 53.58432865,
       40.78109254, 55.71811234, 54.2527128 , 56.81058112, 40.54007115,
       70.52620783, 63.22470577, 57.69521618, 43.22372632, 47.03401836,
       28.97748833, 48.00165466, 71.73842698, 37.52742304, 51.98172885,
       57.34803391, 57.41755739, 49.01645846, 33.08949587, 65.21620897,
       39.61447705, 42.17251209, 63.5533675 , 42.781654  , 56.54811737,
       69.15969194, 79.85508881, 52.65939775, 55.24895095, 25.02788133,
       53.41684087, 70.66442396, 66.46380514, 60.97209853, 35.03092712,
       67.14698559, 48.74835399, 52.11919334, 48.33736313, 40.87015201,
       67.45499601, 59.44455922, 28.89546143, 21.45931815, 52.75897558,
       66.46402404, 54.75069448, 29.84292348, 46.45938347, 59.99354392,
       59.97431973, 49.35800168, 42.27172116, 34.70319504, 78.5511658 ,
       44.60020813, 55.68527755, 39.55886367, 43.72878256, 33.24784179,
       25.97675756, 43.06166618, 44.06095479, 57.78365023, 46.33221886,
       47.82697078, 44.388277  , 55.95753054, 55.97322518, 79.46071862,
       74.3960914 , 54.62940392, 71.32458186, 53.47588534, 40.87623846,
       30.8468402 , 66.89035063, 49.92486792, 61.02453923, 45.52157039,
       72.82480077, 33.17004063, 48.57347407, 58.15668722, 30.99798379,
       63.34865121, 19.1143008 , 57.83051326, 26.50971676, 51.44608434,
       84.77810388, 31.09003276, 31.51029222, 46.55708653, 59.77818052,
       48.29497857, 51.66713297, 43.32131999, 36.97198385, 51.98882608,
       54.52397381, 54.04122848, 36.06704007])

In [ ]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.25694490003270076
Training Efficiency : 0.15911889354813902

In [ ]:
print("mae: ",mean_absolute_error(ytest,ypred))
print("R2 Score :", r2_score(ytest, ypred))

mae:  15.845227813621658
R2 Score : 0.15911889354813902